apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: comp-prog-server
  name: comp-prog-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: comp-prog-server
status:
  loadBalancer: {}
