  eval $(minikube docker-env)
  version: '3'

services:
  #Mysql Database
  comp-prog-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=compprogdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  #Spring Boot comp prog server
  comp-prog-server:
    image: comp-prog-server
    build: .
    depends_on:
      - comp-prog-mysql
    restart: on-failure
    environment:
      - SPRING_DATASOURCER_URL=jdbc:mysql://comp-prog-mysql:3306/compprogdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  mysql-volume:
    driver: "local"
