version: '3'

services:
  #Mysql Database for comp prog server
  comp-prog-db:
    image: mysql:8.0
    container_name: comp-prog-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  #Spring Boot comp prog server
  comp-prog-server:
    container_name: comp-prog-server
    build: .
    depends_on:
      - comp-prog-db
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
    ports:
      - 8080:8080